### ISSUE TITLE
No module named 'selene'

### ISSUE THREAD

**Issue by miladxandi** [MycroftAI/selene-backend#347]
**Describe the bug**
```
(env) root@cowsel:/var/www/selene-backend/api/sso# /usr/local/bin/pipenv run uwsgi --ini uwsgi.ini
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.22 (64bit) on [Thu Oct 12 11:42:50 2023] ***
compiled with version: 7.5.0 on 12 October 2023 09:38:43
os: Linux-4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023
nodename: cowsel
machine: x86_64
clock source: unix
detected number of CPU cores: 20
current working directory: /var/www/selene-backend/api/sso
detected binary path: /var/www/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 80012
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.7.5 (default, Dec  9 2021, 17:04:37)  [GCC 8.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x564d255389c0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 23383)
spawned uWSGI worker 1 (pid: 23387, cores: 1)
spawned uWSGI worker 2 (pid: 23388, cores: 1)
spawned uWSGI worker 3 (pid: 23389, cores: 1)
spawned uWSGI worker 4 (pid: 23390, cores: 1)
Traceback (most recent call last):
  File "./sso_api/api.py", line 29, in <module>
    from selene.api import get_base_config, selene_api, SeleneResponse
ModuleNotFoundError: No module named 'selene'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "./sso_api/api.py", line 29, in <module>
Traceback (most recent call last):
  File "./sso_api/api.py", line 29, in <module>
    from selene.api import get_base_config, selene_api, SeleneResponse
ModuleNotFoundError: No module named 'selene'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
    from selene.api import get_base_config, selene_api, SeleneResponse
ModuleNotFoundError: No module named 'selene'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "./sso_api/api.py", line 29, in <module>
    from selene.api import get_base_config, selene_api, SeleneResponse
ModuleNotFoundError: No module named 'selene'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
^CSIGINT/SIGTERM received...killing workers...
^Cworker 1 buried after 0 seconds
worker 2 buried after 0 seconds
worker 3 buried after 0 seconds
worker 4 buried after 0 seconds
goodbye to uWSGI.

```

I am using pip and python source & virtualenv to run because some commands did not work carefully. Please help to get out of this hole.

**Comment by miladxandi** [comment]
I have a new Issue:
```
File "/var/www/selene-backend/api/sso/sso_api/api.py", line 37, in <module>
    from .endpoints import (
ImportError: attempted relative import with no known parent package
```
